apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellonode-deployment
  labels:
    app: hellonode
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellonode
  template:
    metadata:
      labels:
        app: hellonode
    spec:
      containers:
      - name: hellonode
        image: macksarc2/hellonode:1.0.0
        ports:
        - containerPort: 3000
