apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hellonode
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/macksarc2/hellonode.git
    targetRevision: "1.0.0"
    path: helm-charts/hellonode
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
