apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    path: mysql/
    repoURL: https://github.com/macksarc2/hellonode.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true  # Enable resource pruning
      selfHeal: true  # Automatically sync out-of-sync resources
    syncOptions:
      - CreateNamespace=true  # Automatically create the target namespace if it doesn't exist