apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-network-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              role: frontend  # Allow access from frontend pods
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: mysql  # Ensure this matches the MySQL backend pod label
      ports:
        - protocol: TCP
          port: 3306  # MySQL port for egress access
